genre_index:
    path:     /
    defaults: { _controller: "VDM_campingBundle:Genre:index" }
    methods:  GET

genre_show:
    path:     /{id}/show
    defaults: { _controller: "VDM_campingBundle:Genre:show" }
    methods:  GET

genre_new:
    path:     /new
    defaults: { _controller: "VDM_campingBundle:Genre:new" }
    methods:  [GET, POST]

genre_edit:
    path:     /{id}/edit
    defaults: { _controller: "VDM_campingBundle:Genre:edit" }
    methods:  [GET, POST]

genre_delete:
    path:     /{id}/delete
    defaults: { _controller: "VDM_campingBundle:Genre:delete" }
    methods:  DELETE
