vdm.camping_vdm:
    resource: "@VDM_campingBundle/Resources/config/routing/vdm.yml"
    prefix:   /vdm

vdm.camping_homepage:
    path:     /
    defaults: { _controller: VDM_campingBundle:Default:index }