VDM_campingBundle\Entity\Vdm:
    type: entity
    table: null
    repositoryClass: VDM_campingBundle\Repository\VdmRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        text:
            type: text
        date:
            type: datetime
        auteur:
            type: string
            length: 255
    manyToOne:
        genre:
            targetEntity: VDM_campingBundle\Entity\Genre
            joinColumn:
                name: genre_id
                referencedColumnNamed: id
    lifecycleCallbacks: {  }