<?php

namespace VDM_campingBundle\Repository;

/**
 * VdmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VdmRepository extends \Doctrine\ORM\EntityRepository
{
}
